module.exports = Object.freeze({
    LIMIT_PART_COUNT: "LIMIT_PART_COUNT",
    LIMIT_FILE_SIZE: "LIMIT_FILE_SIZE",
    LIMIT_FILE_COUNT: "LIMIT_FILE_COUNT",
    LIMIT_FIELD_KEY: "LIMIT_FIELD_KEY",
    LIMIT_FIELD_VALUE: "LIMIT_FIELD_VALUE",
    LIMIT_FIELD_COUNT: "LIMIT_FIELD_COUNT",
    LIMIT_UNEXPECTED_FILE: "LIMIT_UNEXPECTED_FILE",
    UNSUPPORTED_MEDIA_TYPE: "UNSUPPORTED_MEDIA_TYPE",
    FORM_DATA_FILE_FIELD: "file",
    MIME_TYPES: ['image/jpeg', "video/mp4"]
})