version: "3"
services:
  nsfw-service:
    container_name: nsfw-service
    build:
      context: .
      dockerfile: Dockerfile
    expose:
      - "8080"
    networks:
      - main-greenbundle-docker-net
networks:
  main-greenbundle-docker-net:
    external: true