version: "3"
services:
  nsfw-service:
    restart: on-failure
    container_name: nsfw-service
    image: nsfw-service:${VERSION:-latest}
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      TZ: America/Argentina/Buenos_Aires
    expose:
      - "8080"
    networks:
      - main-greenbundle-docker-net
    logging:
      driver: fluentd
      options:
        tag: efk.nsfw-service

networks:
  main-greenbundle-docker-net:
    external: true