version: "3"
services:
  nsfw-service:
    container_name: nsfw-service
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:8080"
    networks:
      - greenbundle-containers-network
networks:
  greenbundle-containers-network:
    external: true